name: CI

on:
  # runs on pushes to the main branch
  push:
    branches: [main]
  # also runs inside pull requests that target the main branch
  pull_request:
    branches: [main]

jobs:
  build:
    # uses a Ubuntu Docker image (like a virtual machine)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"
          cache: "npm"
      - name: Set up environment
        env:
          GITHUB_ENV: env/development.env
        run: |
          set -a
          . $GITHUB_ENV
          set +a
      - name: Run your commands using the environment variables from the .env file
        run: |
          echo $YOUR_ENV_VARIABLE
      # install dependencies
      - run: npm ci
      # run ESLint
      - run: npm run lint
      # run test
      - run: npm run test:no-reloading
      # verify that there are no build errors
      - run: npm run build